# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 04 Oct 2009 12:38:41 +0200
*	@user	8
*	@ALL	0
*	potif	4
gite	@inte	2
inte	@inte	2
organisation_globale	@inte	2
poly_inte	@inte	2
pot_if	potif	1
pot_if_communication	potif	1
pot_if_demarches	potif	1
pot_if_equipe	potif	1
pot_if_financement	potif	1
pot_if_soiree	potif	1
semaine_d_integration	@inte	2
start	@ALL	1
start	@user	2
start	@inte	0
start	potif	1
video	@inte	2
wei	@inte	2
bus	@inte	2
jeux_gonflables	@inte	2
tee_shirts	@inte	2
budget	@inte	2
responsables	@inte	2
gestion_alcool	@inte	2
visite_campus	@inte	2
visite_depart	@inte	2
soiree_kfet	@inte	2
pastis_petanque	@inte	2
sortie_terreaux	@inte	2
rallye_bar	@inte	2
repas_flams	@inte	2
soiree_jeux	@inte	2
rallye_lyon	@inte	2
bbq_feyssine	@inte	2
soiree_chouille	@inte	2
