<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: guigouz
 * Date: Sat, 08 May 2010 16:07:12 +0200
 */

$conf['title'] = 'AEDI';
$conf['lang'] = 'fr';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
